---
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: kubernetes.core
  - name: community.crypto
  - name: community.vmware
    version: 1.17.0
  - name: community.general
  - name: infra.controller_configuration
