apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: assisted-service-config
  namespace: open-cluster-management
  labels:
    app: assisted-service
data:
  LOG_LEVEL: "debug"
  AUTH_TYPE: "none"
  SKIP_CERT_VERIFICATION: "True"
  #ENABLE_KUBE_API_DAY2: "true"