---
# tasks file for create_spoke_manifests
- name: Run preflights
  block:
    - name: Run general preflight
      ansible.builtin.include_tasks: preflight.yml

    - name: Run preflights for Tower/Controller
      ansible.builtin.include_tasks: preflight_tower.yml

- name: Setup needed variables
  block:
    - name: Setup Proxy and Root CA configuration
      ansible.builtin.include_tasks: ca_and_proxy.yml

    - name: Setup Ignition Config Overrides
      ansible.builtin.include_tasks: ignition_config_overrides.yml

    - name: Setup variables for Git
      ansible.builtin.include_tasks: git_setup.yml

    - name: Read in the SSH Public Key
      ansible.builtin.include_tasks: ssh_key.yml

- name: Create the ArgoCD cluster Application
  when: create_argo_application | bool
  block:
    - name: Set up the local file system and clone the repo down
      ansible.builtin.include_tasks: git_pull_push_argoapp.yml

- name: Set up the local file system and clone the repo down
  ansible.builtin.include_tasks: git_clone.yml

- name: Template the needed YAML manifests
  ansible.builtin.include_tasks: template_yaml.yml

- name: Git Push
  ansible.builtin.include_tasks: git_push.yml
  vars:
    git_target_branch: "{{ deployment_type }}-{{ cluster_type }}-{{ cluster_name }}"
