---
# =============================================================
## Credential Generation Switches
create_aap2_controller_secret: true
create_pull_secret_secret: true
create_ssh_key_secret: true
create_vsphere_credentials_secret: true
create_git_push_credentials_secret: true

# =============================================================
## AAP2 Controller Secret Variables
aap2_operator_namespace: aap
aap2_controller_name: ac-tower

# =============================================================
## Pull Secret Variables
pull_secret_path: ~/rh-ocp-pull-secret.json
pull_secret: "{{ lookup('file', pull_secret_path) }}"
encoded_pull_secret: "{{ pull_secret | to_json | b64encode }}"

# =============================================================
# Vcenter Credentials
vcenter_secret_name: loe-rdu-vcenter-credentials
vcenter_username: administrator@vsphere.local
vcenter_password: noteMyPassword
vcenter_fqdn: vcenter.lab.kemo.network
vcenter_validate_ssl: false

# =============================================================
# Git Push Credentials
query_gitea_for_url: false
git_push_credentials_secret_name: git-push-credentials
git_push_repo_url: 'http://gitea.gitea.svc.cluster.local:3000/user-1/openshift-ztp'
git_push_username: user-1
git_push_password: openshift

# =============================================================
## Optional Proxy Configuration Variables
## Used when configuring via the AAP2 Controller
#http_proxy: 'http://192.168.42.31:3128/'
#https_proxy: 'http://192.168.42.31:3128/'
#no_proxy: ".cluster.local,.svc,.svc.cluster.local,10.128.0.0/14,127.0.0.1,172.30.0.0/16,192.168.51.0/24,api-int.core-ocp.lab.kemo.network,api.core-ocp.lab.kemo.network,localhost,127.0.0.1,.apps.core-ocp.lab.kemo.network"