vcenter_credential_secret_name: "loe-rdu-vcenter-credentials"
cluster_type: sno
cluster_name: sno-ocp
base_domain: lab.kemo.network
cluster_location: loe-rdu

source_git_repo: https://gitea-gitea.apps.core-ocp.lab.kemo.network/user-1/openshift-ztp.git
git_push_credentials_secret_name: "git-push-credentials"
cluster_node_network_ipam: "dhcp"
cluster_node_cidr: "192.168.42.0/24"

vcenter_datacenter: LabDC
vcenter_cluster: LabCluster
vcenter_datastore: nvme
vcenter_network: VMNetwork
template_secrets: true

cluster_nodes:
  - name: sno-white
    type: sno-node
    vm:
      cpu_cores: 8
      cpu_sockets: 1
      cpu_threads: 1
      memory: 65536
      disks:
        - size: 240
          name: boot
    interfaces:
      - name: ens192
        mac_address: 00:50:56:68:47:10
        dhcp: true
