---
#########################################################################################
## General Variables
credentials_namespace: ztp-credentials

#########################################################################################
## Proxy Configuration for the Ansible Job Execution Environment
## These proxy variables are used by the Ansible Execution Environment as environment variables
http_proxy: 'http://192.168.51.1:3128/'
https_proxy: 'http://192.168.51.1:3128/'
no_proxy: ".cluster.local,.svc,.svc.cluster.local,10.128.0.0/14,127.0.0.1,172.30.0.0/16,192.168.51.0/24,api-int.core-ocp.lab.kemo.network,api.core-ocp.lab.kemo.network,localhost,127.0.0.1,.apps.core-ocp.lab.kemo.network"

#########################################################################################
## Local AAP2 Controller Secret, created from AAP2 Controller local App+Token configuration
create_aap2_controller_secret: true
aap2_controller_secret_name: ansible-tower-credentials

## With these two variables provided, the AAP2 Controller credentials/route will be read dynamically
## from a Secret called `aap2-controller-admin-application-token`
aap2_operator_namespace: ansible-automation-platform
aap2_controller_name: ac-tower

#########################################################################################
## vCenter credentials
create_vsphere_credentials_secret: true
vcenter_secret_name: loe-rdu-vcenter-credentials

vcenter_username: administrator@vsphere.local
vcenter_password: Passw0rd!
vcenter_fqdn: vcenter.example.com
vcenter_validate_ssl: true

#########################################################################################
## Git Push Credentials used by the create_spoke_manifests.yml and deploy_to_vsphere.yml playbook
create_git_push_credentials_secret: true
git_push_credentials_secret_name: git-push-credentials

# query_gitea_for_url will query the Hub hosted Gitea instance for the URL of the repo
query_gitea_for_url: false #default is true
git_push_repo_url: 'http://gitea.gitea.svc.cluster.local:3000/user-1/openshift-ztp'

git_push_branch: main
git_push_user_name: ZTPBot
git_push_user_email: ztp-bot@notredhat.com

git_push_credentials_auth_method: basic # ssh or basic

## Basic Auth Credentials to git push to the repo
git_push_username: user-1
git_push_password: openshift

## SSH Auth, Public Key Text
git_push_ssh_key: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAA...

#########################################################################################
## Pull Secret for Spoke Cluster Pulling Images
create_pull_secret_secret: true
pull_secret_secret_name: ztp-deployment-pull-secret

## If running locally, you can reference it by path
pull_secret_path: '/some/path/to/pull-secret.json'

## If pasting in or passing along the pull secret, it must be encoded first with an empty pull_secret variable
pull_secret: ""
encoded_pull_secret: |
  base64EncodedPullSecretJSON