---
## vCenter credentials
vcenter_secret_name: loe-rdu-vcenter-credentials
vcenter_username: administrator@vsphere.local
vcenter_password: Passw0rd!
vcenter_fqdn: vcenter.example.com

## Git Push Credentials used by the create_spoke_manifests.yml playbook
create_git_push_credentials_secret: true
git_push_credentials_secret_name: git-push-credentials
git_push_username: user-1
git_push_password: openshift
query_gitea_for_url: false
git_push_repo_url: 'http://gitea.gitea.svc.cluster.local:3000/user-1/openshift-ztp'

## Proxy Configuration for the Ansible Job Execution Environment
http_proxy: 'http://192.168.51.1:3128/'
https_proxy: 'http://192.168.51.1:3128/'
no_proxy: ".cluster.local,.svc,.svc.cluster.local,10.128.0.0/14,127.0.0.1,172.30.0.0/16,192.168.51.0/24,api-int.core-ocp.lab.kemo.network,api.core-ocp.lab.kemo.network,localhost,127.0.0.1,.apps.core-ocp.lab.kemo.network"

## Pull Secret for Images
pull_secret: '{"auths":{"cloud.openshift.com":"..."}}'
