apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ztp-mirror
  namespace: ztp-mirror
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
