---
# tasks file for deploy_vault_chart
- name: Template the Hashicorp Helm Chart Repository
  kubernetes.core.k8s:
    state: present
    template: templates/chart-repository.yml.j2

- name: Create the Hashicorp Vault Project - {{ vault_namespace }}
  kubernetes.core.k8s:
    state: present
    kind: Namespace
    api_version: v1
    merge_type:
    - strategic-merge
    - merge
    definition:
      metadata:
        name: "{{ vault_namespace }}"
      spec: {}

- name: Deploy the latest version of the Hashicorp Vault Helm Chart
  kubernetes.core.helm:
    name: vault
    chart_ref: hashicorp/vault
    release_namespace: "{{ vault_namespace }}"
    values:
      global.openshift: true
      server.dev.enabled: false