FROM registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:1.0.1-72

RUN microdnf update -y
RUN microdnf install git which -y

RUN python3 -m pip install --upgrade --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org openshift kubernetes pyvmomi jmespath PyYAML jsonpatch
