---

- name: Set empty facts
  set_fact:
    mac_interfaces_count: 0

- name: Setup VMWare disk dictionary
  set_fact:
    disks: "{{ disks | default([]) + [{ 'size_gb' : disk_item.size, 'type' : 'thin' }] }}"
  loop: "{{ node_item.vm.disks }}"
  loop_control:
    loop_var: disk_item

- name: Setup VMWare network dictionary
  set_fact:
    networks: "{{ networks | default([]) + [{ 'name' : cluster_configmap_info.resources[0].data.vsphere_network, 'device_type' : 'vmxnet3', 'mac' : iface_item.mac_address|default('') }] }}"
  loop: "{{ node_item.interfaces }}"
  loop_control:
    loop_var: iface_item

- name: Setup VMWare network mac address count when mac_address is defined
  when: iface_item.mac_address is defined
  set_fact:
    mac_interfaces_count: "{{ (mac_interfaces_count|int + 1) }}"
  loop: "{{ node_item.interfaces }}"
  loop_control:
    loop_var: iface_item

- name: Setup Agent Names
  set_fact:
    agent_names: "{{ agent_names | default([]) + [node_item.name] }}"

- name: Create VM when a resource pool is not defined
  when: node_item.vm.resource_pool is not defined
  community.vmware.vmware_guest:
    hostname: '{{ vsphere_secret.resources[0].data.vcenter_fqdn | b64decode }}'
    username: '{{ vsphere_secret.resources[0].data.vcenter_username | b64decode }}'
    password: '{{ vsphere_secret.resources[0].data.vcenter_password | b64decode }}'
    validate_certs: "{{ (vsphere_secret.resources[0].data.skip_ssl_validation|b64decode == 'true') | ternary('false', 'true') }}"
    datacenter: "{{ cluster_configmap_info.resources[0].data.vsphere_datacenter }}"
    datastore: "{{ cluster_configmap_info.resources[0].data.vsphere_datastore }}"
    cluster: "{{ cluster_configmap_info.resources[0].data.vsphere_cluster }}"
    name: "{{ cluster_configmap_info.resources[0].data.cluster_name }}-{{ node_item.name }}"
    folder: "{{ cluster_configmap_info.resources[0].data.vsphere_vm_folder | default(cluster_configmap_info.resources[0].data.cluster_name) }}"
    guest_id: coreos64Guest
    state: present
    disk: "{{ disks }}"
    hardware:
      memory_mb: "{{ node_item.vm.memory }}"
      num_cpu_cores_per_socket : "{{ node_item.vm.cpu_cores * node_item.vm.cpu_threads|int }}"
      num_cpus : "{{ (node_item.vm.cpu_sockets|int * node_item.vm.cpu_cores|int * node_item.vm.cpu_threads|int ) }}"
    cdrom:
    - controller_number: 0
      unit_number: 0
      state: present
      type: iso
      iso_path: "[{{ cluster_configmap_info.resources[0].data.vsphere_datastore }}] {{ cluster_configmap_info.resources[0].data.vsphere_iso_folder | default('ISOs') }}/discovery-iso-{{ cluster_configmap_info.resources[0].data.cluster_name }}.iso"
    networks: "{{ networks }}"

- name: Create VM when a resource pool is defined
  when: node_item.vm.resource_pool is defined
  community.vmware.vmware_guest:
    hostname: '{{ vsphere_secret.resources[0].data.vcenter_fqdn | b64decode }}'
    username: '{{ vsphere_secret.resources[0].data.vcenter_username | b64decode }}'
    password: '{{ vsphere_secret.resources[0].data.vcenter_password | b64decode }}'
    validate_certs: "{{ (vsphere_secret.resources[0].data.skip_ssl_validation|b64decode == 'true') | ternary('false', 'true') }}"
    datacenter: "{{ cluster_configmap_info.resources[0].data.vsphere_datacenter }}"
    datastore: "{{ cluster_configmap_info.resources[0].data.vsphere_datastore }}"
    cluster: "{{ cluster_configmap_info.resources[0].data.vsphere_cluster }}"
    name: "{{ cluster_configmap_info.resources[0].data.cluster_name }}-{{ node_item.name }}"
    folder: "{{ cluster_configmap_info.resources[0].data.vsphere_vm_folder | default(cluster_configmap_info.resources[0].data.cluster_name) }}"
    guest_id: coreos64Guest
    state: present
    disk: "{{ disks }}"
    resource_pool: "{{ node_item.vm.resource_pool }}"
    hardware:
      memory_mb: "{{ node_item.vm.memory }}"
      num_cpu_cores_per_socket : "{{ node_item.vm.cpu_cores * node_item.vm.cpu_threads|int }}"
      num_cpus : "{{ (node_item.vm.cpu_sockets|int * node_item.vm.cpu_cores|int * node_item.vm.cpu_threads|int ) }}"
    cdrom:
    - controller_number: 0
      unit_number: 0
      state: present
      type: iso
      iso_path: "[{{ cluster_configmap_info.resources[0].data.vsphere_datastore }}] {{ cluster_configmap_info.resources[0].data.vsphere_iso_folder | default('ISOs') }}/discovery-iso-{{ cluster_configmap_info.resources[0].data.cluster_name }}.iso"
    networks: "{{ networks }}"

- name: Power on the VM if it has all interfaces defined with mac addresses
  when: mac_interfaces_count|int == node_item.interfaces|length
  community.vmware.vmware_guest:
    hostname: '{{ vsphere_secret.resources[0].data.vcenter_fqdn | b64decode }}'
    username: '{{ vsphere_secret.resources[0].data.vcenter_username | b64decode }}'
    password: '{{ vsphere_secret.resources[0].data.vcenter_password | b64decode }}'
    validate_certs: "{{ (vsphere_secret.resources[0].data.skip_ssl_validation|b64decode == 'true') | ternary('false', 'true') }}"
    datacenter: "{{ cluster_configmap_info.resources[0].data.vsphere_datacenter }}"
    datastore: "{{ cluster_configmap_info.resources[0].data.vsphere_datastore }}"
    cluster: "{{ cluster_configmap_info.resources[0].data.vsphere_cluster }}"
    name: "{{ cluster_configmap_info.resources[0].data.cluster_name }}-{{ node_item.name }}"
    folder: "{{ cluster_configmap_info.resources[0].data.vsphere_vm_folder | default(cluster_configmap_info.resources[0].data.cluster_name) }}"
    guest_id: coreos64Guest
    state: poweredon

- name: Get the VM Configuration and reconfigure NMState otherwise
  when: mac_interfaces_count|int != node_item.interfaces|length
  block:
    - name: Get the VM Information
      community.vmware.vmware_guest_info:
        hostname: '{{ vsphere_secret.resources[0].data.vcenter_fqdn | b64decode }}'
        username: '{{ vsphere_secret.resources[0].data.vcenter_username | b64decode }}'
        password: '{{ vsphere_secret.resources[0].data.vcenter_password | b64decode }}'
        validate_certs: "{{ (vsphere_secret.resources[0].data.skip_ssl_validation|b64decode == 'true') | ternary('false', 'true') }}"
        name: "{{ cluster_configmap_info.resources[0].data.cluster_name }}-{{ node_item.name }}"
        datacenter: "{{ cluster_configmap_info.resources[0].data.vsphere_datacenter }}"
      register: vm_guest_info

    - name: debug vm_guest_info
      debug:
        msg: "{{ vm_guest_info }}"

    - name: Loop through the hw_interfaces for their Info
      debug:
        msg: "{{ vm_guest_info.instance[interface_item] }}"
      loop: "{{ vm_guest_info.instance.hw_interfaces }}"
      loop_control:
        loop_var: interface_item
        label: "{{ interface_item }}"

- name: Resetting Facts
  set_fact:
    networks: []
    disks: []
    agent_names: []
    vm_guest_info: {}