apiVersion: gpte.opentlc.com/v1
kind: Gitea
metadata:
  name: gitea
spec:
  giteaSsl: true
  giteaAdminUser: opentlc-mgr
  giteaAdminPassword: "r3dh4t123!"
  giteaAdminEmail: opentlc-mgr@redhat.com
  giteaImageTag: latest
  giteaVolumeSize: 10Gi
  giteaVolumeStorageClass: ocs-storagecluster-cephfs
  postgresqlVolumeSize: 4Gi
  postgresqlVolumeStorageClass: ocs-storagecluster-cephfs
  giteaCreateUsers: true
  giteaGenerateUserFormat: "user-%d"
  giteaUserNumber: 2
  giteaUserPassword: openshift
  giteaMigrateRepositories: true
  giteaRepositoriesList:
  - repo: https://github.com/Red-Hat-SE-RTO/openshift-ztp.git
    name: openshift-ztp
    private: true