apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  creationTimestamp: null
  name: hive
  namespace: open-cluster-management
  labels:
    installer.name: multiclusterhub
    installer.namespace: open-cluster-management
spec:
  featureGates:
    custom:
      enabled:
        - AlphaAgentInstallStrategy
    featureSet: Custom
  logLevel: debug
  targetNamespace: hive