FROM registry.redhat.io/ansible-automation-platform-22/platform-resource-runner-rhel8@sha256:9bf9ec1759a3b101d249bcf47aa4fd967b33f0c71538e4aa706a73bdf50346b4

COPY container_root/ /

RUN update-ca-trust