---
- name: Configure a Hub OpenShift Cluster for ZTP
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    #########################################
    output_lines: []
    configure_rhacm: true
    configure_aap2_controller: true
    configure_rh_gitops: true

    use_ztp_mirror: true
    use_services_not_routes: true

    ## Path to the OpenShift Pull Secret
    pull_secret_path: ~/rh-ocp-pull-secret.json
    pull_secret: "{{ lookup('file', pull_secret_path) }}"

    # git_credential_type: ssh | basic
    scm_credential_type: basic
    scm_credential_username: user-1
    scm_credential_password: openshift
    scm_credential_private_key: ~/.ssh/id_rsa
    scm_credential_public_key: ~/.ssh/id_rsa.pub
    scm_repo_name: openshift-ztp

  tasks:
    - name: Configure RHACM for ZTP feature gated functions
      when: configure_rhacm|bool
      include_role:
        name: configure_rhacm_oas

    - name: Configure Ansible Automation Platform 2 Controller for ZTP stuff
      when: configure_aap2_controller|bool
      include_role:
        name: configure_aap2_controller

    - name: Configure ArgoCD/Red Hat GitOps for syncing ZTP Spoke Clusters
      when: configure_rh_gitops|bool
      include_role:
        name: configure_argocd

    - name: Print the Playbook output
      when: output_lines | length > 0
      debug:
        msg: "{{ output_lines }}"
