---
- name: Post Cluster Automation - Configure the Spoke Cluster with an Identity Provider for AAD
  hosts: all
  gather_facts: no

  tasks:
    - name: debug facts
      vars:
        msg: |
          Module Variables ("vars"):
          --------------------------------
          {{ vars | to_nice_json }}
          
          Environment Variables ("environment"):
          --------------------------------
          {{ environment | to_nice_json }}
          
          GROUP NAMES Variables ("group_names"):
          --------------------------------
          {{ group_names | to_nice_json }}
          
          GROUPS Variables ("groups"):
          --------------------------------
          {{ groups | to_nice_json }}
          
          HOST Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_json }}
    
      debug:
        msg: "{{ msg.split('\n') }}"