galaxy_info:
  author: Ken Moini
  description: Deploys the NFD Operator
  company: Red Hat

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  issue_tracker_url: https://github.com/Red-Hat-SE-RTO/openshift-ztp/issues

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - openshift
    - ztp

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
